apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops6
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mlops6
  template:
    metadata:
      labels:
        app: mlops6
    spec:
      containers:
      - name: mlops6
        image: us-central1-docker.pkg.dev/lofty-voyage-461011-f1/mlops6/mlops6_image:latest
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: mlops-service
spec:
  selector:
    app: mlops6
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
